@URL = http://localhost:8000

# TODO: /root must be ok
GET {{URL}}

# TODO: /reports must output a list of reports with their status
GET {{URL}}

# TODO: /report/submit must let us submit a new report for processing
#   accepted formats are JSON and CSV, anything else should result in an error
PUT {{URL}}

# TODO: Accessing specific report before it is ready should result in an error
GET {{URL}}